name: Bug report
description: Report a bug in the project

title: 'Test'
labels: bug
assignees: 'NA'

body: |
  ## Description
  A clear and concise description of what the bug is.

  ## Steps to Reproduce
  1. 
  2. 
  3. 

  ## Expected Behavior
  A clear and concise description of what you expected to happen.

  ## Actual Behavior
  A clear and concise description of what actually happened.

  ## Screenshots (if applicable)
  Add screenshots to help explain your problem.

  ## Environment (please complete the following information)
  - OS: 
  - Browser: 
  - Version: 

  ## Additional context
  Add any other context about the problem here.
