name: Bug report
description: Report a bug in the project

title: 'Test'
labels: bug
assignees: 'NA'

body:
- type: markdown
  attributes:
    value: "Bugs are the worst!"
- type: textarea
  attributes:
    label: "What's wrong?"
